plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
//    id 'kotlin-kapt'
    id 'kotlin-parcelize'
    id("com.google.devtools.ksp") version '2.3.6'
}

android {
    namespace 'ir.androidir.SelfAccounting'
    compileSdk 34

    buildFeatures {
        viewBinding = true
    }

    defaultConfig {
        applicationId "ir.androidir.SelfAccounting"
        minSdk 23
        targetSdk 34
        versionCode 28
        versionName "1.20"


        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    // RoomDB =>
    implementation "androidx.room:room-runtime:2.8.4"
    ksp("androidx.room:room-compiler:2.8.4")

    // Circle chart =>
    implementation 'com.mikhaellopez:circularprogressbar:3.1.0'

    // Poolakey =>
    implementation "com.github.cafebazaar.Poolakey:poolakey:2.2.0"

    // Work Manager =>
    implementation "androidx.work:work-runtime-ktx:2.9.1"

    // Gson =>
    implementation 'com.google.code.gson:gson:2.11.0'
}